
!ifndef DEBUG
DEBUG = 0
!endif

MAKE = nmake.exe -nologo -s

ALL:
	cd ADO1
	@$(MAKE) DEBUG=$(DEBUG) 
	cd ..\AsmCtrl
	@$(MAKE) DEBUG=$(DEBUG) 
	cd ..\DDraw1
	@$(MAKE) DEBUG=$(DEBUG) 
	cd ..\DDraw2
	@$(MAKE) DEBUG=$(DEBUG) 
#	cd ..\DInput1
#	@$(MAKE) DEBUG=$(DEBUG) 
#	cd ..\Dir3D1
#	@$(MAKE) DEBUG=$(DEBUG) 
	cd ..\DSound1
	@$(MAKE) DEBUG=$(DEBUG) 
	cd ..\DSound2
	@$(MAKE) DEBUG=$(DEBUG) 
	cd ..\GdiPlus
	@$(MAKE) DEBUG=$(DEBUG) 
	cd ..\LVSample
	@$(MAKE) DEBUG=$(DEBUG) 
	cd ..\ODBC1
	@$(MAKE) DEBUG=$(DEBUG) 
	cd ..\OpenGL1
	@$(MAKE) DEBUG=$(DEBUG) 
	cd ..\PlayMidi
	@$(MAKE) DEBUG=$(DEBUG) 
	cd ..\ReadTOC
	@$(MAKE) DEBUG=$(DEBUG) 
#	cd ..\RpcSmpl
#	@$(MAKE) DEBUG=$(DEBUG) 
	cd ..\SEHSmpl
	@$(MAKE) DEBUG=$(DEBUG) 
	cd ..\ShFolder
	@$(MAKE) DEBUG=$(DEBUG) 
#	cd ..\SimplSvr
#	@$(MAKE) DEBUG=$(DEBUG) 
	cd ..\SockHttp
	@$(MAKE) DEBUG=$(DEBUG) 
	cd ..\Toolhelp
	@$(MAKE) DEBUG=$(DEBUG) 
	cd ..\WinCUI1
	@$(MAKE) DEBUG=$(DEBUG) 
	cd ..\WinCUI2
	@$(MAKE) DEBUG=$(DEBUG) 
	cd ..\WinGUI1
	@$(MAKE) DEBUG=$(DEBUG) 
	cd ..\WinGUI2
	@$(MAKE) DEBUG=$(DEBUG) 
	cd ..\WinINet
	@$(MAKE) DEBUG=$(DEBUG) 
	cd ..\WinUni1
	@$(MAKE) DEBUG=$(DEBUG) 
	cd ..



clean: 
	cd ADO1
	@$(MAKE) DEBUG=$(DEBUG) clean
	cd ..\AsmCtrl
	@$(MAKE) DEBUG=$(DEBUG) clean 
	cd ..\DDraw1
	@$(MAKE) DEBUG=$(DEBUG) clean 
	cd ..\DDraw2
	@$(MAKE) DEBUG=$(DEBUG) clean 
	cd ..\DInput1
	@$(MAKE) DEBUG=$(DEBUG) clean 
	cd ..\Dir3D1
	@$(MAKE) DEBUG=$(DEBUG) clean 
	cd ..\DSound1
	@$(MAKE) DEBUG=$(DEBUG) clean 
	cd ..\DSound2
	@$(MAKE) DEBUG=$(DEBUG) clean 
	cd ..\GdiPlus
	@$(MAKE) DEBUG=$(DEBUG) clean 
	cd ..\LVSample
	@$(MAKE) DEBUG=$(DEBUG) clean 
	cd ..\ODBC1
	@$(MAKE) DEBUG=$(DEBUG) clean 
	cd ..\OpenGL1
	@$(MAKE) DEBUG=$(DEBUG) clean 
	cd ..\PlayMidi
	@$(MAKE) DEBUG=$(DEBUG) clean 
	cd ..\ReadTOC
	@$(MAKE) DEBUG=$(DEBUG) clean 
	cd ..\RpcSmpl
	@$(MAKE) DEBUG=$(DEBUG) clean 
	cd ..\SEHSmpl
	@$(MAKE) DEBUG=$(DEBUG) clean 
	cd ..\ShFolder
	@$(MAKE) DEBUG=$(DEBUG) clean 
	cd ..\SimplSvr
	@$(MAKE) DEBUG=$(DEBUG) clean 
	cd ..\SockHttp
	@$(MAKE) DEBUG=$(DEBUG) clean 
	cd ..\Toolhelp
	@$(MAKE) DEBUG=$(DEBUG) clean 
	cd ..\WinCUI1
	@$(MAKE) DEBUG=$(DEBUG) clean 
	cd ..\WinCUI2
	@$(MAKE) DEBUG=$(DEBUG) clean 
	cd ..\WinGUI1
	@$(MAKE) DEBUG=$(DEBUG) clean 
	cd ..\WinGUI2
	@$(MAKE) DEBUG=$(DEBUG) clean 
	cd ..\WinINet
	@$(MAKE) DEBUG=$(DEBUG) clean 
	cd ..\WinUni1
	@$(MAKE) DEBUG=$(DEBUG) clean 
	cd ..

