;--- include file created by h2incx v0.92, copyright 2005 japheth
;--- source file: c:\programme\devstudio\vc6\include\cguid.h, last modified: 4/24/1998 0:0
ifndef __CGUID_H__
__CGUID_H__	EQU	<>
ifdef __cplusplus 
;extern "C"{ 
endif 
externdef GUID_NULL: IID
externdef IID_IRpcChannel: IID
externdef IID_IRpcStub: IID
externdef IID_IStubManager: IID
externdef IID_IRpcProxy: IID
externdef IID_IProxyManager: IID
externdef IID_IPSFactory: IID
externdef IID_IInternalMoniker: IID
externdef IID_IDfReserved1: IID
externdef IID_IDfReserved2: IID
externdef IID_IDfReserved3: IID
externdef CLSID_StdMarshal: CLSID
externdef CLSID_AggStdMarshal: CLSID
externdef CLSID_StdAsyncActManager: CLSID
externdef IID_IStub: IID
externdef IID_IProxy: IID
externdef IID_IEnumGeneric: IID
externdef IID_IEnumHolder: IID
externdef IID_IEnumCallback: IID
externdef IID_IOleManager: IID
externdef IID_IOlePresObj: IID
externdef IID_IDebug: IID
externdef IID_IDebugStream: IID
externdef CLSID_PSGenObject: CLSID
externdef CLSID_PSClientSite: CLSID
externdef CLSID_PSClassObject: CLSID
externdef CLSID_PSInPlaceActive: CLSID
externdef CLSID_PSInPlaceFrame: CLSID
externdef CLSID_PSDragDrop: CLSID
externdef CLSID_PSBindCtx: CLSID
externdef CLSID_PSEnumerators: CLSID
externdef CLSID_StaticMetafile: CLSID
externdef CLSID_StaticDib: CLSID
externdef CID_CDfsVolume: CLSID
externdef CLSID_DCOMAccessControl: CLSID
externdef CLSID_StdGlobalInterfaceTable: CLSID
externdef CLSID_ComBinding: CLSID
endif
