;--- include file created by h2incx v0.99.20 (copyright 2005-2009 japheth)
;--- source file: C:\WinInc\GdiPlus\GdiPlus.h, last modified: 3/26/2003 15:34
;--- cmdline used for creation: GdiPlus.h

ifndef _GDIPLUS_H
_GDIPLUS_H	EQU	<>
INT16 typedef SWORD
UINT16 typedef WORD
	include pshpack8.inc
;	include GdiplusMem.inc
;	include GdiplusBase.inc
	include GdiplusEnums.inc
	include GdiplusTypes.inc
	include GdiplusInit.inc
	include GdiplusPixelFormats.inc
	include GdiplusColor.inc
;	include GdiplusMetaHeader.inc
	include GdiplusImaging.inc
	include GdiplusColorMatrix.inc
	include GdiplusGpStubs.inc
;	include GdiplusHeaders.inc

	include GdiplusFlat.inc

;	include GdiplusImageAttributes.inc
;	include GdiplusMatrix.inc
;	include GdiplusBrush.inc
;	include GdiplusPen.inc
;	include GdiplusStringFormat.inc
;	include GdiplusPath.inc
;	include GdiplusLineCaps.inc
;	include GdiplusMetafile.inc
;	include GdiplusGraphics.inc
;	include GdiplusCachedBitmap.inc
;	include GdiplusRegion.inc
;	include GdiplusFontCollection.inc
;	include GdiplusFontFamily.inc
;	include GdiplusFont.inc
;	include GdiplusBitmap.inc
;	include GdiplusImageCodec.inc

	include poppack.inc
endif 

;--- errors: 0
;--- end of file ---
