
# WinINet sample 
# either JWASM/JWLINK (default) or MASM/MSLINK is to be used.

!ifndef MASM
MASM=0
MSLINK=0
!else
MSLINK=1
!endif

NAME=WinINet
OUTDIR=.

!ifndef DEBUG
DEBUG=0
!endif

!if $(DEBUG)
!if $(MSLINK)
LOPTD=/DEBUG:FULL
!else
LOPTD=debug c op cvp
!endif
AOPTD=-Zi
!else
LOPTD=
AOPTD=
!endif

ASMOPT= -c -nologo -coff -Fl$* -Sg -I..\..\Include $(AOPTD)
!if $(MASM)
ASM=@ml.exe $(ASMOPT)
!else
ASM=@jwasm.exe $(ASMOPT)
!endif

LIBS=kernel32.lib user32.lib msvcrt.lib wininet.lib

!if $(MSLINK)
LOPTS= /MAP /LIBPATH:..\..\Lib /SUBSYSTEM:windows /OPT:NOWIN98
LINK=@link.exe $(LOPTD) $(LOPTS) $* rsrc.res $(LIBS)
RC=@rc.exe -i..\..\Include -fo$*.res 
!else
LOPTS= LibPath ..\..\Lib op MAP, quiet, res=rsrc.res, map
LINK=@jwlink.exe $(LOPTD) format windows pe runtime windows file $(OUTDIR)\$(NAME).obj $(LOPTS) lib {$(LIBS)}
RC=@wrc -q -r -i=..\..\Include
!endif

$(OUTDIR)\$(NAME).exe: $*.obj rsrc.res
	$(LINK)

$(OUTDIR)\$(NAME).obj: $(NAME).asm Makefile
	$(ASM) -Fo$*.obj $(NAME).asm

$(OUTDIR)\rsrc.res: rsrc.rc
	$(RC) rsrc.rc

CLEAN :
	-@erase "$(OUTDIR)\$(NAME).exe"
	-@erase "$(OUTDIR)\$(NAME).obj"
	-@erase "$(OUTDIR)\$(NAME).lst"
	-@erase "$(OUTDIR)\$(NAME).map"
	-@erase "$(OUTDIR)\rsrc.res"
